---
title: "dataCleaning"
author: "Carter Melnick"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r}
# Converts a comma separated string into a list of values
listify <- function(s) {
  as.list(strsplit(s, ", ")[[1]])
}

dollar <- function(s) {
  newStr <- as.numeric(sub(".* ", "", s))
  scales::dollar(newStr)
}

convertDollar <- function(str) {
  ifelse(is.na(str), str, 
         ifelse(substr(str, 1, 1) == "$", dollar(str), str))
}

currency <- function(s) {
  num <- as.integer(sub(".* ", "", s))
  id <- sub(" .*", "", s)
  formattedNum <- as.character(scales::comma(num))
  paste0(id, formattedNum)
}

convertCurrency <- function(str) {
  ifelse(is.na(str), str, currency(str))
}

isDollar <- function(str) {
  ifelse(is.na(str), str, 
         ifelse(substr(str, 1, 1) == "$", TRUE, FALSE))
}

asNum <- function(str) {
  ifelse(is.na(str), str, 
         ifelse(substr(str, 1, 1) == "$", as.integer(sub(".* ", "", str)), str))
}
```


```{r message=FALSE, warning=FALSE}
# Load in full datasets
# Source: https://www.kaggle.com/stefanoleone992/imdb-extensive-dataset
# Dataset includes all movies with more than 100 votes
movies <- read_csv("IMDbmovies.csv")
movies$index <- seq(1, nrow(movies))
moviesFinal <- movies %>% mutate(genreList = strsplit(genre, ", "),
                                 primaryGenre = as.character(map(genreList, 1)),
                                 countryList = strsplit(country, ", "),
                                 primaryCountry = as.character(map(countryList, 1)),
                                 languageList = strsplit(language, ", "),
                                 primaryLanguage = as.character(map(languageList, 1)),
                                 budgetNum = asNum(budget),
                                 incomeNum = asNum(worlwide_gross_income),
                                 budget = convertDollar(budget),
                                 usa_gross_income = convertDollar(usa_gross_income),
                                 worlwide_gross_income = convertDollar(worlwide_gross_income),
                                 isDollar = isDollar(budget),
                                 size=1) %>%
                          # These two genres each only had 2 movies
                          filter(primaryGenre != "Adult", primaryGenre != "Documentary") %>%
                          select(-c(genreList,countryList, languageList))
```

```{r}
write_csv(moviesFinal, "movies.csv")
```

```{r}
currency <- function(s) {
  if(substr(s, 1, 1) == "$") {
    dollar(s)
  } else {
    num <- as.integer(sub(".* ", "", s))
    id <- sub(" .*", "", s)
    formattedNum <- as.character(scales::comma(num))
    paste(id, formattedNum)
  }
}

convertCurrency <- function(str) {
  ifelse(is.na(str), str, currency(str))
}
```























